# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b33Vt6_KHcWD7oZ-P6n8ZMuMdi8yuuHI
"""

# ============================================================
# DATA4400 A3 - ABS Food Retailing Forecasting
# Upload Excel file → Run Holt-Winters/ETS forecast → Create visuals
# ============================================================

# Install required packages
!pip -q install pandas openpyxl statsmodels xlsxwriter matplotlib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from sklearn.metrics import mean_absolute_error, mean_squared_error
from google.colab import files
import os
import zipfile

# ------------------------------------------------------------
# 1. Upload Excel file
# ------------------------------------------------------------
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

print("Uploaded file:", file_name)

# ------------------------------------------------------------
# 2. Read Excel file
# ------------------------------------------------------------
df = pd.read_excel(file_name)

print("\nOriginal columns:")
print(df.columns.tolist())

# Clean column names
df.columns = df.columns.astype(str).str.strip()

# ------------------------------------------------------------
# 3. Auto-detect date column and value column
# ------------------------------------------------------------

# Try to find date/month column
possible_date_cols = [
    col for col in df.columns
    if "date" in col.lower() or "month" in col.lower() or "period" in col.lower()
]

if possible_date_cols:
    date_col = possible_date_cols[0]
else:
    date_col = df.columns[0]

# Try to find turnover/sales/value column
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()

possible_value_cols = [
    col for col in numeric_cols
    if "turnover" in col.lower()
    or "sales" in col.lower()
    or "value" in col.lower()
    or "food" in col.lower()
]

if possible_value_cols:
    value_col = possible_value_cols[0]
else:
    value_col = numeric_cols[-1]

print("\nDetected date column:", date_col)
print("Detected value column:", value_col)

# ------------------------------------------------------------
# 4. Prepare monthly time series
# ------------------------------------------------------------

data = df[[date_col, value_col]].copy()
data.columns = ["Month", "Turnover"]

# Convert Month to datetime
data["Month"] = pd.to_datetime(data["Month"], errors="coerce")

# Remove bad rows
data = data.dropna(subset=["Month", "Turnover"])

# Convert turnover to numeric
data["Turnover"] = pd.to_numeric(data["Turnover"], errors="coerce")
data = data.dropna(subset=["Turnover"])

# Convert dates to month start
data["Month"] = data["Month"].dt.to_period("M").dt.to_timestamp()

# Sort chronologically
data = data.sort_values("Month")

# If duplicate months exist, average them
data = data.groupby("Month", as_index=False)["Turnover"].mean()

# Set time index
ts = data.set_index("Month")["Turnover"]

# Ensure monthly frequency
ts = ts.asfreq("MS")

print("\nCleaned time series preview:")
print(ts.head())

print("\nData period:")
print(ts.index.min(), "to", ts.index.max())

# ------------------------------------------------------------
# 5. Holdout accuracy test
# Last 12 months used as test period
# ------------------------------------------------------------

test_periods = 12

train = ts.iloc[:-test_periods]
test = ts.iloc[-test_periods:]

holdout_model = ExponentialSmoothing(
    train,
    trend="add",
    seasonal="add",
    seasonal_periods=12
).fit(optimized=True)

holdout_forecast = holdout_model.forecast(test_periods)

# Accuracy metrics
mae = mean_absolute_error(test, holdout_forecast)
rmse = np.sqrt(mean_squared_error(test, holdout_forecast))
mape = np.mean(np.abs((test - holdout_forecast) / test)) * 100

print("\nHoldout Accuracy Results:")
print("MAE:", round(mae, 2))
print("RMSE:", round(rmse, 2))
print("MAPE:", round(mape, 2), "%")

# ------------------------------------------------------------
# 6. Final model using full dataset
# Forecast next 12 months
# ------------------------------------------------------------

final_model = ExponentialSmoothing(
    ts,
    trend="add",
    seasonal="add",
    seasonal_periods=12
).fit(optimized=True)

forecast_steps = 12
forecast = final_model.forecast(forecast_steps)

forecast_df = pd.DataFrame({
    "Month": forecast.index,
    "Forecast_Turnover_Million_AUD": forecast.values
})

print("\nForecast output:")
print(forecast_df)

# ------------------------------------------------------------
# 7. Create visuals
# ------------------------------------------------------------

output_folder = "forecast_outputs"
os.makedirs(output_folder, exist_ok=True)

# Visual 1: Actual turnover line chart
plt.figure(figsize=(10, 5))
plt.plot(ts.index, ts.values, marker="o")
plt.title("Monthly Food Retailing Turnover: Jan 2021 – Jun 2025")
plt.xlabel("Month")
plt.ylabel("Turnover AUD Millions")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig(f"{output_folder}/actual_turnover_line.png", dpi=300)
plt.show()

# Visual 2: Actual vs forecast
plt.figure(figsize=(10, 5))
plt.plot(ts.index, ts.values, marker="o", label="Actual")
plt.plot(forecast.index, forecast.values, marker="o", linestyle="--", label="Forecast")
plt.title("Actual vs Forecast Food Retailing Turnover")
plt.xlabel("Month")
plt.ylabel("Turnover AUD Millions")
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig(f"{output_folder}/actual_vs_forecast.png", dpi=300)
plt.show()

# Visual 3: Holdout accuracy actual vs predicted
plt.figure(figsize=(10, 5))
plt.plot(test.index, test.values, marker="o", label="Actual")
plt.plot(holdout_forecast.index, holdout_forecast.values, marker="o", linestyle="--", label="Predicted")
plt.title("Holdout Test: Actual vs Predicted")
plt.xlabel("Month")
plt.ylabel("Turnover AUD Millions")
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig(f"{output_folder}/holdout_accuracy.png", dpi=300)
plt.show()

# Visual 4: Monthly seasonality bar chart
seasonality = data.copy()
seasonality["Month_Name"] = seasonality["Month"].dt.month_name()
seasonality["Month_Number"] = seasonality["Month"].dt.month

seasonal_avg = (
    seasonality
    .groupby(["Month_Number", "Month_Name"])["Turnover"]
    .mean()
    .reset_index()
    .sort_values("Month_Number")
)

plt.figure(figsize=(10, 5))
plt.bar(seasonal_avg["Month_Name"], seasonal_avg["Turnover"])
plt.title("Average Monthly Food Retailing Turnover Seasonality")
plt.xlabel("Month")
plt.ylabel("Average Turnover AUD Millions")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig(f"{output_folder}/seasonality_bar.png", dpi=300)
plt.show()

# ------------------------------------------------------------
# 8. Export Excel model file
# ------------------------------------------------------------

actual_df = ts.reset_index()
actual_df.columns = ["Month", "Actual_Turnover_Million_AUD"]

holdout_df = pd.DataFrame({
    "Month": test.index,
    "Actual": test.values,
    "Predicted": holdout_forecast.values
})

holdout_df["Absolute_Error"] = abs(holdout_df["Actual"] - holdout_df["Predicted"])
holdout_df["APE_%"] = abs((holdout_df["Actual"] - holdout_df["Predicted"]) / holdout_df["Actual"]) * 100
holdout_df["Squared_Error"] = (holdout_df["Actual"] - holdout_df["Predicted"]) ** 2

metrics_df = pd.DataFrame({
    "Metric": ["MAE", "RMSE", "MAPE"],
    "Value": [mae, rmse, mape]
})

excel_output = "DATA4400_A3_forecast_model_python.xlsx"

with pd.ExcelWriter(excel_output, engine="xlsxwriter") as writer:
    actual_df.to_excel(writer, sheet_name="Cleaned_Time_Series", index=False)
    forecast_df.to_excel(writer, sheet_name="Forecast_12_Months", index=False)
    holdout_df.to_excel(writer, sheet_name="Holdout_Accuracy", index=False)
    metrics_df.to_excel(writer, sheet_name="Accuracy_Metrics", index=False)
    seasonal_avg.to_excel(writer, sheet_name="Seasonality", index=False)

print("\nExcel model saved as:", excel_output)

# ------------------------------------------------------------
# 9. Create ZIP file with model + visuals
# ------------------------------------------------------------

zip_name = "DATA4400_A3_forecast_outputs.zip"

with zipfile.ZipFile(zip_name, "w") as zipf:
    zipf.write(excel_output)
    for file in os.listdir(output_folder):
        zipf.write(os.path.join(output_folder, file))

print("ZIP file saved as:", zip_name)

# ------------------------------------------------------------
# 10. Download files
# ------------------------------------------------------------

files.download(excel_output)
files.download(zip_name)